### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by BigSeanZzz** [BShakhovsky/PolyphonicPianoTranscription#10]
Hello

I have many problems while setting up this project，I guess it's because of the versions of packages and compatibility between them.
Can you please provide the requirements？
Especially the version of TensorFlow, Magenta, Keras.

Thank you very much

**Comment by BShakhovsky** [comment]
Hello,
 
Last time I ran the templates several months ago, and the versions were the following:
Python 3.8.8
Tensorflow 2.4.0
Keras 2.4.3
Magenta 2.1.3

**Comment by BigSeanZzz** [comment]
> Hello,
> 
> Last time I ran the templates several months ago, and the versions were the following: Python 3.8.8 Tensorflow 2.4.0 Keras 2.4.3 Magenta 2.1.3

got it， thank you
