### ISSUE TITLE
cannot import name 'sequence_to_valued_intervals' from 'magenta.models.onsets_frames_transcription.metrics'

### ISSUE THREAD

**Issue by Apichai9888** [BShakhovsky/PolyphonicPianoTranscription#11]
Hello

Thank you these notebooks of onsets_and_frames model.

Previously, file 2 Training, Validation, Testing.ipynb that use magenta 2.1.3 is work but now in magenta 2.1.4 isn't work.

I try to run your code but found a problem that run on google colab.

ImportError: cannot import name 'sequence_to_valued_intervals' from 'magenta.models.onsets_frames_transcription.metrics' (/usr/local/lib/python3.7/dist-packages/magenta/models/onsets_frames_transcription/metrics.py)

I would like to ask you how to fix.
Thank you so much.

![1](https://user-images.githubusercontent.com/89087280/187158800-620d8eeb-a377-45bb-bebe-049a14f0b38f.jpg)
![2](https://user-images.githubusercontent.com/89087280/187158850-b2bf14ff-c72a-4963-946a-fb989c99835d.jpg)

**Comment by BShakhovsky** [comment]
Hello,
 
It seems that __*sequence_to_valued_intervals*__ function has been moved to __*note_seq*__ library, and here is that Magenta’s commit:
https://github.com/magenta/magenta/pull/1880
 
So, the following line:
`from magenta.models.onsets_frames_transcription.metrics import sequence_to_valued_intervals`
should be changed to the following:
`from note_seq.sequences_lib import sequence_to_valued_intervals`

**Comment by Apichai9888** [comment]
Thank you very much
