### ISSUE TITLE
No module named 'magenta.models.onsets_frames_transcription.split_audio_and_label_data'

### ISSUE THREAD

**Issue by Apichai9888** [BShakhovsky/PolyphonicPianoTranscription#9]
Hello

Thank you so much for these notebooks and the explanation of onsets_and_frames model.
I'm new. I try  to run your code but found a problem that run on google colab. 
" No module named 'magenta.models.onsets_frames_transcription.split_audio_and_label_data' "
I would like to ask you how to fix.
Thank you so much.

![image](https://user-images.githubusercontent.com/89087280/129744785-60eab06f-b4f5-4a85-903a-7725ae638c1a.png)

**Comment by BShakhovsky** [comment]
Hello,
 
I have looked for __*find_split_points*__ function at Magenta’s GitHub repository, and it seems that they renamed __*split_audio_and_label_data*__ python file to __*audio_label_data_utils*__. Here is that Magenta’s commit:
https://github.com/magenta/magenta/commit/3414c43e69fbb66c7a1a3f218d3e1c22e6e5863d
 
So, the following line:
`from magenta.models.onsets_frames_transcription.split_audio_and_label_data import find_split_points`
should be changed to the following:
`from magenta.models.onsets_frames_transcription.audio_label_data_utils import find_split_points`
 
I currently do not have access to my laptop and cannot check it, but most probably this fix should work.
